[theme]
primaryColor = "#5B9BD5"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#31333F"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[client]
# Possible values: "dots", "circle", "square", "hamburger", "arrow", "balloon", "ripple"
spinnerType = "hamburger"
showErrorDetails = false
toolbarMode = "minimal"
caching = true
displayEnabled = true 